print('Здравствуй, мир!')
print('Как тебя зовут?')
my_name = input()
print('Рад познакомиться с тобой, ' + my_name)
print('Длина твоего имени: ')
print(len(my_name), 'буквы')
print('Сколько тебе лет?')
my_age = input()
print('Через год тебе будет ' + str(int(my_age) + 1) + ' лет.')
